### ISSUE TITLE
Downgrade starlette version

### ISSUE THREAD

**Issue by lewoudar** [bigbag/starlette-i18n#12]
Hi @bigbag,
first of all, thank you for this package, I was struggling with this i18n stuff!

I don't know if there is a good reason to set `starlette` version to the last one, but if it is not the case, can you consider downgrade it to something like `starlette>=14.0.0` ? This will make some FastAPI users happy since the latter will always be late to catch up starlette version.

**Comment by bigbag** [comment]
Hi!
I have relaxed requires in version 0.8.0, now we have 
`starlette>=0.12,<1.0`

**Comment by lewoudar** [comment]
Thanks!
