### ISSUE TITLE
Is starlette-i18n limited to provide only one extra locale?

### ISSUE THREAD

**Issue by boamaod** [bigbag/starlette-i18n#15]
Do I understand correctly that starlette-i18n cannot provide more than one translation locale at a time? Examples [here](https://github.com/bigbag/starlette-i18n/tree/main/examples) also deliver only one extra locale besides English as the default language. Is that intentional and expresses a limitation of using starlette-i18n and more generally jinja2.ext.i18n for ASGI frameworks like Starlette?

I found related discussions at https://github.com/encode/starlette/issues/279#issuecomment-505068010 and https://github.com/pallets/jinja/issues/1323#issuecomment-738955649, but maybe you @bigbag as the author of this localisation helper have further comments and maybe some practical suggestions on this?

**Comment by bigbag** [comment]
Hi. yes, it is correct one translation locale by one request. I do not know examples as you need more one locale for request
For example user one with locale CN and user two with DE makes two request with different locales and every user get response with correct locale.

**Comment by bigbag** [comment]
> Examples [here](https://github.com/bigbag/starlette-i18n/tree/main/examples) also deliver only one extra locale besides English as the default language.

It is only example. You can use so many locales as you need. For example we use this library with 10 different locales.

**Comment by boamaod** [comment]
> It is only example. You can use so many locales as you need. For example we use this library with 10 different locales.

And users haven't reported translations being slightly mixed up or performance issues in cases of high load of the website?

> I found related discussions at [encode/starlette#279 (comment)](https://github.com/encode/starlette/issues/279#issuecomment-505068010) and [pallets/jinja#1323 (comment)](https://github.com/pallets/jinja/issues/1323#issuecomment-738955649), but maybe you @bigbag as the author of this localisation helper have further comments and maybe some practical suggestions on this?

In first discussion I referred Starlette developers seem to agree that Jinja2 i18n extension is not suitable for ASGI, because it uses global language state. In the second discussion the same point of using global gettext instead of isolated context for each locale is made in Jinja2 issue tracker referring to Aiohttp. How have you overcome this issue of Jinja i18n extension using global gettext functions, @bigbag? Since starlette-i18n seems to provide a wrapper for Jinja2 i18n extension, it has to handle these problems somehow, doesn't it?
