### ISSUE TITLE
Example with Jinja2?

### ISSUE THREAD

**Issue by michaeltoohig** [bigbag/starlette-i18n#7]
Do you have an example of using this with Jinja2 templates? I found this discussion saying to use dictionaries to translate in templates but perhaps there is a better way with your project. https://github.com/encode/starlette/issues/279

**Comment by bigbag** [comment]
Sorry for waiting.
it seems for me that this example can help you https://github.com/bigbag/starlette-i18n/tree/main/examples

**Comment by michaeltoohig** [comment]
Thank you, I've already gone forward with using a dictionary for my current project but it is not ideal and will implement this in the future.
